=== AlphinK/CAT1/CHC.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Studio 2021 (https://www.liquid-tEmp-designationhnologies.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOSLAurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Emp-name" type="xs:string"></xs:element>
                            <xs:element name="Emp-age" type="xs:string"></xs:element>
                            <xs:element name="tname" type="xs:string"></xs:element>
                            <xs:element name="Emp-salary" type="xs:integer"></xs:element>
                            <xs:element name="Emp-emailid" type="xs:integer"></xs:element>
                            <xs:element name="Emp-Phonenum" type="xs:integer"></xs:element>
                            <xs:element name="Emp-designation" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="tname">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[a-z]"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
</xs:schema>

=== AlphinK/CAT1/Railway.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xEmp-designation" href="CH.xEmp-designation"?>
<Company  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="CHC.xsd">
    <menu>
        <employee id="t100">
            <Emp-name>New delhi</Emp-name>
            <Emp-age>kannur</Emp-age>
            <tname>  IRCTC TEJAS EXP </tname>
            <Emp-salary>400</Emp-salary>
            <Emp-emailid>1250</Emp-emailid>
            <Emp-Phonenum> 250</Emp-Phonenum>
            <Emp-designation>1783</Emp-designation>
        </employee>

         <employee id="t101">
            <Emp-name>Agomoni</Emp-name>
            <Emp-age>Ajanti</Emp-age>
            <tname>  SHRAM SHKTI EXP </tname>
            <Emp-salary> 300</Emp-salary>
            <Emp-emailid>1250</Emp-emailid>
            <Emp-Phonenum> 250</Emp-Phonenum>
            <Emp-designation>1783</Emp-designation>
        </employee>
         <employee id="t102">
            <Emp-name>North Bengal</Emp-name>
            <Emp-age>Goa</Emp-age>
            <tname>  ANVT REWA EXP </tname>
            <Emp-salary> 400</Emp-salary>
            <Emp-emailid>1250</Emp-emailid>
            <Emp-Phonenum> 250</Emp-Phonenum>
            <Emp-designation>1783</Emp-designation>
        </employee>
         <employee id="t103">
            <Emp-name>Lucknow</Emp-name>
            <Emp-age>West Bengal</Emp-age>
            <tname>  VIKRAMSHILA EXP </tname>
            <Emp-salary> 400</Emp-salary>
            <Emp-emailid>1250</Emp-emailid>
            <Emp-Phonenum> 250</Emp-Phonenum>
            <Emp-designation>1783</Emp-designation>
        </employee>
         <employee id="t104">
            <Emp-name>New delhi</Emp-name>
            <Emp-age>Odisha</Emp-age>
            <tname>  NANDANKANAN EXP </tname>
            <Emp-salary> 400</Emp-salary>
            <Emp-emailid>1250</Emp-emailid>
            <Emp-Phonenum> 250</Emp-Phonenum>
            <Emp-designation>1783</Emp-designation>
        </employee>
         <employee id="t105">
            <Emp-name>Andhra Pradesh</Emp-name>
            <Emp-age>Kerala</Emp-age>
            <tname>  JHARKHAND EXP </tname>
            <Emp-salary> 400</Emp-salary>
            <Emp-emailid>1250</Emp-emailid>
            <Emp-Phonenum> 250</Emp-Phonenum>
            <Emp-designation>1783</Emp-designation>
        </employee>
         <employee id="t106">
            <Emp-name>Gujarat</Emp-name>
            <Emp-age>Chennai</Emp-age>
            <tname>  BIHAR S KRANTI </tname>
            <Emp-salary> 400</Emp-salary>
            <Emp-emailid>1250</Emp-emailid>
            <Emp-Phonenum> 250</Emp-Phonenum>
            <Emp-designation>1783</Emp-designation>
        </employee>
         <employee id="t107">
            <Emp-name>Jaipur</Emp-name>
            <Emp-age>Kannur</Emp-age>
            <tname>  PURUSHOTTAM EXP </tname>
            <Emp-salary> 400</Emp-salary>
            <Emp-emailid>1250</Emp-emailid>
            <Emp-Phonenum> 250</Emp-Phonenum>
            <Emp-designation>1783</Emp-designation>
        </employee>
    </menu>

</Company>
